import { useState, useEffect, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { CheckCircle2, Circle, Calendar, AlertCircle, Plus, Filter, X, RefreshCw, Edit2, ChevronDown, ChevronRight } from 'lucide-react';
import { useWeddingData } from '../contexts/WeddingDataContext';
import { Task } from '../lib/storage-adapter';
import { taskCategories, standardTasks, TaskTemplate } from './taskTemplates';
import TimelineView from './TimelineView';

export default function TodosModule() {
  const { t } = useTranslation();
  const { weddingData, tasks, events, vendors, locations, supportTeam, addTask, updateTask, updateEvent, deleteTask, initializeAutoTasks, dismissTaskWarning, updateWeddingData } = useWeddingData();
  const [showGenerateDialog, setShowGenerateDialog] = useState(false);
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [showRecalculateDialog, setShowRecalculateDialog] = useState(false);
  const [showEditDialog, setShowEditDialog] = useState(false);
  const [editingTask, setEditingTask] = useState<Task | null>(null);
  const [filterCategory, setFilterCategory] = useState<string>('all');
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [view, setView] = useState<'list' | 'timeline'>('list');
  const [isMobile, setIsMobile] = useState(false);
  const [expandedTasks, setExpandedTasks] = useState<Set<string>>(new Set());
  const [expandedCategories, setExpandedCategories] = useState<Set<string>>(new Set());

  const [newTask, setNewTask] = useState({
    title: '',
    description: '',
    category: 'planning',
    due_date: '',
    priority: 'medium' as 'high' | 'medium' | 'low',
  });

  useEffect(() => {
    const checkMobile = () => setIsMobile(window.innerWidth < 768);
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  const handleEnableAutoTasks = async () => {
    await initializeAutoTasks();
  };

  const handleSkipAutoTasks = () => {
    updateWeddingData({ auto_tasks_initialized: true });
  };

  const generateStandardTasks = () => {
    if (!weddingData?.wedding_date) return;

    const weddingDate = new Date(weddingData.wedding_date + 'T12:00:00');
    const today = new Date();
    const planningStart = weddingData.planning_start_date
      ? new Date(weddingData.planning_start_date + 'T12:00:00')
      : today;

    const totalDays = Math.ceil((weddingDate.getTime() - planningStart.getTime()) / (1000 * 60 * 60 * 24));

    if (totalDays <= 0) {
      alert('Das Planungsstartdatum muss vor dem Hochzeitsdatum liegen!');
      return;
    }

    const sortedTemplates = [...standardTasks].sort((a, b) => b.weeks_before_wedding - a.weeks_before_wedding);

    const maxWeeks = sortedTemplates[0].weeks_before_wedding;
    const minWeeks = sortedTemplates[sortedTemplates.length - 1].weeks_before_wedding;

    const taskIdMap = new Map<string, string>();

    sortedTemplates.forEach((template: TaskTemplate, index: number) => {
      const normalizedPosition = (template.weeks_before_wedding - minWeeks) / (maxWeeks - minWeeks);

      const daysFromStart = Math.round(totalDays * (1 - normalizedPosition));

      const dueDate = new Date(planningStart);
      dueDate.setDate(dueDate.getDate() + daysFromStart);

      if (dueDate > weddingDate) {
        dueDate.setTime(weddingDate.getTime());
      }

      const startDate = new Date(dueDate);
      startDate.setDate(startDate.getDate() - 7);

      if (startDate < planningStart) {
        startDate.setTime(planningStart.getTime());
      }

      const task = addTask({
        title: template.title,
        description: template.description,
        category: template.category,
        start_date: startDate.toISOString().split('T')[0],
        due_date: dueDate.toISOString().split('T')[0],
        completed: false,
        priority: template.priority,
        depends_on: [],
        is_system_generated: template.isAutoGenerated,
      });

      taskIdMap.set(template.category, task.id);
    });

    setShowGenerateDialog(false);
  };

  const recalculateAutoTaskDates = () => {
    if (!weddingData?.wedding_date) {
      alert('Bitte zuerst ein Hochzeitsdatum in den Einstellungen festlegen!');
      return;
    }

    const weddingDate = new Date(weddingData.wedding_date + 'T12:00:00');
    const planningStart = weddingData.planning_start_date
      ? new Date(weddingData.planning_start_date + 'T12:00:00')
      : new Date();

    const totalDays = Math.ceil((weddingDate.getTime() - planningStart.getTime()) / (1000 * 60 * 60 * 24));

    if (totalDays <= 0) {
      alert('Das Planungsstartdatum muss vor dem Hochzeitsdatum liegen!');
      return;
    }

    const sortedTemplates = [...standardTasks].sort((a, b) => b.weeks_before_wedding - a.weeks_before_wedding);
    const maxWeeks = sortedTemplates[0].weeks_before_wedding;
    const minWeeks = sortedTemplates[sortedTemplates.length - 1].weeks_before_wedding;

    const autoTasks = tasks.filter(task => task.is_system_generated && !task.completed);

    autoTasks.forEach(task => {
      const template = standardTasks.find(t => t.title === task.title);
      if (!template) return;

      const normalizedPosition = (template.weeks_before_wedding - minWeeks) / (maxWeeks - minWeeks);
      const daysFromStart = Math.round(totalDays * (1 - normalizedPosition));

      const dueDate = new Date(planningStart);
      dueDate.setDate(dueDate.getDate() + daysFromStart);

      if (dueDate > weddingDate) {
        dueDate.setTime(weddingDate.getTime());
      }

      const startDate = new Date(dueDate);
      startDate.setDate(startDate.getDate() - 7);

      if (startDate < planningStart) {
        startDate.setTime(planningStart.getTime());
      }

      if (task.manually_modified) {
        updateTask(task.id, {
          date_change_notice: '⚠️ Durch die Änderung des Hochzeitsdatums hat sich das optimale Zeitfenster geändert. Bitte überprüfe die Deadline.',
          completed: false,
        });
      } else {
        deleteTask(task.id);
        addTask({
          title: template.title,
          description: template.description,
          category: template.category,
          start_date: startDate.toISOString().split('T')[0],
          due_date: dueDate.toISOString().split('T')[0],
          completed: false,
          priority: template.priority,
          depends_on: [],
          is_system_generated: template.isAutoGenerated,
        });
      }
    });

    setShowRecalculateDialog(false);
  };

  const filteredTasks = useMemo(() => {
    return tasks.filter(task => {
      if (filterCategory !== 'all' && task.category !== filterCategory) return false;
      if (filterStatus === 'completed' && !task.completed) return false;
      if (filterStatus === 'active' && task.completed) return false;
      return true;
    });
  }, [tasks, filterCategory, filterStatus]);

  const sortedTasks = useMemo(() => {
    return [...filteredTasks].sort((a, b) => {
      if (!a.due_date || !b.due_date) return 0;
      return new Date(a.due_date).getTime() - new Date(b.due_date).getTime();
    });
  }, [filteredTasks]);

  const groupedTasks = useMemo(() => {
    const groups = new Map<string, Task[]>();
    sortedTasks.forEach(task => {
      const category = task.category;
      if (!groups.has(category)) {
        groups.set(category, []);
      }
      groups.get(category)!.push(task);
    });
    return groups;
  }, [sortedTasks]);

  useEffect(() => {
    const initialExpanded = new Set<string>();
    groupedTasks.forEach((tasks) => {
      const firstIncomplete = tasks.find(t => !t.completed);
      if (firstIncomplete) {
        initialExpanded.add(firstIncomplete.id);
      }
    });
    setExpandedTasks(initialExpanded);
  }, [groupedTasks.size]);

  const toggleTaskExpansion = (taskId: string) => {
    setExpandedTasks(prev => {
      const newSet = new Set(prev);
      if (newSet.has(taskId)) {
        newSet.delete(taskId);
      } else {
        newSet.add(taskId);
      }
      return newSet;
    });
  };

  const toggleCategoryExpansion = (category: string) => {
    setExpandedCategories(prev => {
      const newSet = new Set(prev);
      if (newSet.has(category)) {
        newSet.delete(category);
      } else {
        newSet.add(category);
      }
      return newSet;
    });
  };

  const completionStats = useMemo(() => {
    const total = tasks.length;
    const completed = tasks.filter(t => t.completed).length;
    const percentage = total > 0 ? Math.round((completed / total) * 100) : 0;
    return { total, completed, percentage };
  }, [tasks]);

  const toggleTaskCompletion = (task: Task) => {
    updateTask(task.id, {
      completed: !task.completed,
      completed_at: !task.completed ? new Date().toISOString() : undefined,
    });
  };

  const handleAddTask = () => {
    if (!newTask.title.trim()) return;

    addTask({
      title: newTask.title,
      description: newTask.description,
      category: newTask.category,
      due_date: newTask.due_date || undefined,
      completed: false,
      priority: newTask.priority,
      is_system_generated: false,
    });

    setNewTask({
      title: '',
      description: '',
      category: 'planning',
      due_date: '',
      priority: 'medium',
    });
    setShowAddDialog(false);
  };

  const handleEditTask = (task: Task) => {
    setEditingTask(task);
    setShowEditDialog(true);
  };

  const handleSaveEdit = () => {
    if (!editingTask) return;

    const originalTask = tasks.find(t => t.id === editingTask.id);
    const template = standardTasks.find(t => t.title === originalTask?.title);

    const isModified = editingTask.is_system_generated && originalTask && (
      template?.title !== editingTask.title ||
      template?.description !== editingTask.description ||
      originalTask.due_date !== editingTask.due_date
    );

    updateTask(editingTask.id, {
      title: editingTask.title,
      description: editingTask.description,
      category: editingTask.category,
      due_date: editingTask.due_date,
      priority: editingTask.priority,
      manually_modified: isModified || editingTask.manually_modified,
      date_change_notice: undefined,
    });

    setEditingTask(null);
    setShowEditDialog(false);
  };

  const dismissDateChangeNotice = (taskId: string) => {
    updateTask(taskId, { date_change_notice: undefined });
  };

  const getBlockedTasks = (task: Task): string[] => {
    if (!task.depends_on || task.depends_on.length === 0) return [];

    return task.depends_on
      .map(depId => tasks.find(t => t.id === depId))
      .filter(t => t && !t.completed)
      .map(t => t!.title);
  };

  const getCategoryColor = (category: string) => {
    const cat = taskCategories.find(c => c.id === category);
    return cat?.color || 'bg-gray-500';
  };

  const showAutoTaskBanner = tasks.length === 0 && weddingData?.wedding_date && !weddingData?.auto_tasks_initialized;

  return (
    <div className="space-y-6">
      {showAutoTaskBanner && (
        <div className="bg-blue-50 border-2 border-blue-500 rounded-lg p-6">
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center flex-shrink-0">
              <Calendar className="w-6 h-6 text-blue-600" />
            </div>
            <div className="flex-1">
              <h3 className="text-lg font-bold text-blue-900 mb-2">
                Automatische Aufgaben erstellen?
              </h3>
              <p className="text-blue-800 mb-4" style={{ fontFamily: 'Open Sans, sans-serif' }}>
                Du hast noch keine Aufgaben. Möchtest du automatische Aufgaben basierend auf deinem Hochzeitsdatum ({new Date(weddingData.wedding_date).toLocaleDateString('de-DE')}) generieren lassen?
              </p>
              <div className="flex gap-3">
                <button
                  onClick={handleEnableAutoTasks}
                  className="px-6 py-2 rounded-md transition-all hover:opacity-90 font-semibold"
                  style={{
                    backgroundColor: '#d6b15b',
                    color: 'white',
                    fontFamily: 'Open Sans, sans-serif',
                  }}
                >
                  Ja, Aufgaben generieren
                </button>
                <button
                  onClick={handleSkipAutoTasks}
                  className="px-6 py-2 rounded-md border-2 transition-all hover:bg-white font-semibold"
                  style={{
                    borderColor: '#d6b15b',
                    color: '#3b3b3d',
                    fontFamily: 'Open Sans, sans-serif',
                  }}
                >
                  Nein, manuell erstellen
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      <div className="flex items-center justify-between flex-wrap gap-4">
        <div className="flex items-center gap-6">
          <div>
            <div className="text-2xl font-bold" style={{ color: '#3b3b3d' }}>
              {completionStats.completed} / {completionStats.total}
            </div>
            <div className="text-sm" style={{ color: '#666' }}>
              Aufgaben erledigt
            </div>
          </div>

          <div className="w-48">
            <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
              <div
                className="h-full bg-emerald-500 transition-all duration-300"
                style={{ width: `${completionStats.percentage}%` }}
              />
            </div>
            <div className="text-xs mt-1" style={{ color: '#666' }}>
              {completionStats.percentage}% abgeschlossen
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <div className="flex rounded-lg overflow-hidden border-2" style={{ borderColor: '#d6b15b' }}>
            <button
              onClick={() => setView('list')}
              className={`px-4 py-2 text-sm font-medium transition-all ${
                view === 'list'
                  ? 'text-white'
                  : 'text-gray-700 bg-white hover:bg-gray-50'
              }`}
              style={view === 'list' ? { backgroundColor: '#d6b15b' } : {}}
            >
              Liste
            </button>
            <button
              onClick={() => setView('timeline')}
              className={`px-4 py-2 text-sm font-medium transition-all ${
                view === 'timeline'
                  ? 'text-white'
                  : 'text-gray-700 bg-white hover:bg-gray-50'
              }`}
              style={view === 'timeline' ? { backgroundColor: '#d6b15b' } : {}}
            >
              Timeline
            </button>
          </div>

          <button
            onClick={() => setShowAddDialog(true)}
            className="px-6 py-2 rounded-md transition-all hover:opacity-90 flex items-center gap-2"
            style={{
              backgroundColor: '#d6b15b',
              color: 'white',
              fontFamily: 'Open Sans, sans-serif',
              fontWeight: 600
            }}
          >
            <Plus className="w-4 h-4" />
            Aufgabe hinzufügen
          </button>

          {tasks.filter(t => t.is_system_generated && !t.completed).length > 0 && (
            <button
              onClick={() => setShowRecalculateDialog(true)}
              className="px-4 py-2 rounded-md border-2 transition-all hover:bg-gray-50 flex items-center gap-2"
              style={{
                borderColor: '#d6b15b',
                color: '#3b3b3d',
                fontFamily: 'Open Sans, sans-serif',
                fontWeight: 600
              }}
              title="Automatische Tasks neu berechnen"
            >
              <RefreshCw className="w-4 h-4" />
              Neu berechnen
            </button>
          )}
        </div>
      </div>

      <div className="flex gap-4 items-center flex-wrap">
        <div className="flex items-center gap-2">
          <Filter className="w-4 h-4" style={{ color: '#666' }} />
          <span className="text-sm font-medium" style={{ color: '#666' }}>
            Filter:
          </span>
        </div>

        <select
          value={filterCategory}
          onChange={(e) => setFilterCategory(e.target.value)}
          className="px-3 py-1.5 rounded-md border-2 text-sm"
          style={{ borderColor: '#d6b15b', fontFamily: 'Open Sans, sans-serif' }}
        >
          <option value="all">Alle Kategorien</option>
          {taskCategories.map(cat => (
            <option key={cat.id} value={cat.id}>{cat.label}</option>
          ))}
        </select>

        <select
          value={filterStatus}
          onChange={(e) => setFilterStatus(e.target.value)}
          className="px-3 py-1.5 rounded-md border-2 text-sm"
          style={{ borderColor: '#d6b15b', fontFamily: 'Open Sans, sans-serif' }}
        >
          <option value="all">Alle Status</option>
          <option value="active">Aktiv</option>
          <option value="completed">Erledigt</option>
        </select>

        <div className="flex gap-2 flex-wrap">
          {taskCategories.map(cat => {
            const count = tasks.filter(t => t.category === cat.id).length;
            return (
              <div
                key={cat.id}
                className="flex items-center gap-1 px-2 py-1 rounded text-xs text-white"
                style={{ backgroundColor: cat.color.replace('bg-', '#') }}
              >
                <span className={`w-3 h-3 rounded ${cat.color}`} />
                <span>{cat.label} ({count})</span>
              </div>
            );
          })}
        </div>
      </div>

      {view === 'timeline' && isMobile && (
        <div className="bg-amber-50 border-2 border-amber-500 rounded-lg p-4 flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <div className="font-semibold text-amber-900 mb-1">
              Desktop empfohlen
            </div>
            <div className="text-sm text-amber-700">
              Für die Timeline-Ansicht nutzen Sie bitte einen Desktop-Browser für die beste Darstellung.
            </div>
          </div>
        </div>
      )}

      {view === 'timeline' ? (
        weddingData?.wedding_date ? (
          <TimelineView
            tasks={sortedTasks}
            events={events}
            vendors={vendors}
            locations={locations}
            supportTeam={supportTeam}
            weddingDate={weddingData.wedding_date}
            onToggleTask={toggleTaskCompletion}
            onEditTask={handleEditTask}
            onUpdateTask={updateTask}
            onUpdateEvent={updateEvent}
            getBlockedTasks={getBlockedTasks}
          />
        ) : (
          <div className="text-center py-12 bg-gray-50 rounded-lg border-2" style={{ borderColor: '#e5e5e5' }}>
            <Calendar className="w-12 h-12 mx-auto mb-3" style={{ color: '#d6b15b' }} />
            <p className="text-gray-600" style={{ fontFamily: 'Open Sans, sans-serif' }}>
              Bitte setzen Sie zuerst ein Hochzeitsdatum in den Einstellungen
            </p>
          </div>
        )
      ) : (
        <div className="space-y-6">
          {sortedTasks.length === 0 ? (
            <div className="text-center py-12 bg-gray-50 rounded-lg border-2" style={{ borderColor: '#e5e5e5' }}>
              <Calendar className="w-12 h-12 mx-auto mb-3" style={{ color: '#d6b15b' }} />
              <p className="text-gray-600" style={{ fontFamily: 'Open Sans, sans-serif' }}>
                Keine Aufgaben vorhanden
              </p>
            </div>
          ) : (
            Array.from(groupedTasks.entries()).map(([category, categoryTasks]) => {
              const categoryInfo = taskCategories.find(c => c.id === category);
              const completedCount = categoryTasks.filter(t => t.completed).length;
              const isCategoryExpanded = expandedCategories.has(category);

              return (
                <div
                  key={category}
                  className="bg-white rounded-lg border-2 hover:shadow-md transition-all"
                  style={{ borderColor: '#d6b15b' }}
                >
                  <div
                    className="flex items-center gap-3 p-4 cursor-pointer hover:bg-gray-50 transition-colors"
                    onClick={() => toggleCategoryExpansion(category)}
                  >
                    <div className="text-3xl flex-shrink-0">
                      {categoryInfo?.icon || '📋'}
                    </div>
                    <h3 className="text-lg font-bold flex-1" style={{ color: '#3b3b3d' }}>
                      {categoryInfo?.label || category}
                    </h3>
                    <span className="text-sm font-medium text-gray-500">
                      {completedCount}/{categoryTasks.length}
                    </span>
                    {isCategoryExpanded ? (
                      <ChevronDown className="w-5 h-5 text-gray-400 flex-shrink-0" />
                    ) : (
                      <ChevronRight className="w-5 h-5 text-gray-400 flex-shrink-0" />
                    )}
                  </div>

                  {isCategoryExpanded && (
                    <div className="divide-y-2 border-t-2" style={{ borderColor: '#f3f4f6' }}>
                      {categoryTasks.map(task => {
                      const isExpanded = expandedTasks.has(task.id);
                      const blockedBy = getBlockedTasks(task);
                      const isBlocked = blockedBy.length > 0;
                      const isOverdue = task.due_date && new Date(task.due_date) < new Date() && !task.completed;

                      return (
                        <div key={task.id}>
                          <div
                            className="flex items-center gap-3 px-4 py-3 cursor-pointer hover:bg-gray-50 transition-colors"
                            onClick={() => toggleTaskExpansion(task.id)}
                          >
                            <button
                              onClick={(e) => {
                                e.stopPropagation();
                                toggleTaskCompletion(task);
                              }}
                              className="flex-shrink-0"
                            >
                              {task.completed ? (
                                <CheckCircle2 className="w-5 h-5 text-emerald-500" />
                              ) : (
                                <Circle className="w-5 h-5 text-gray-400 hover:text-emerald-500 transition-colors" />
                              )}
                            </button>

                            <h4
                              className={`flex-1 font-medium ${task.completed ? 'line-through text-gray-400' : 'text-gray-900'}`}
                              style={{ fontFamily: 'Open Sans, sans-serif' }}
                            >
                              {task.title}
                            </h4>

                            {isExpanded ? (
                              <ChevronDown className="w-5 h-5 text-gray-400" />
                            ) : (
                              <ChevronRight className="w-5 h-5 text-gray-400" />
                            )}
                          </div>

                          {isExpanded && (
                            <div className="px-4 pb-4 bg-gray-50">
                              <div className="pt-3 flex items-start justify-between gap-4">
                                <div className="flex-1">
                                  <div className="flex items-center gap-2 mb-2">
                                    {task.is_system_generated ? (
                                      <>
                                        <span className="text-lg">🤖</span>
                                        <span className="inline-flex items-center px-2 py-0.5 rounded text-xs bg-blue-100 text-blue-700 font-medium">
                                          Empfehlung
                                        </span>
                                        {task.manually_modified && (
                                          <span className="inline-flex items-center px-2 py-0.5 rounded text-xs bg-amber-100 text-amber-700 font-medium">
                                            Angepasst
                                          </span>
                                        )}
                                      </>
                                    ) : (
                                      <>
                                        <span className="text-lg">💍</span>
                                        {task.needs_adjustment_warning && !task.warning_dismissed && (
                                          <span className="inline-flex items-center px-2 py-0.5 rounded text-xs bg-orange-100 text-orange-700 font-medium">
                                            ⚠️ Datum prüfen
                                          </span>
                                        )}
                                      </>
                                    )}
                                  </div>

                                  {task.needs_adjustment_warning && !task.warning_dismissed && !task.is_system_task && (
                                    <div className="mt-2 bg-orange-50 border border-orange-200 rounded-lg p-3">
                                      <div className="flex items-start gap-2">
                                        <AlertCircle className="w-4 h-4 text-orange-600 flex-shrink-0 mt-0.5" />
                                        <div className="flex-1 text-sm text-orange-800">
                                          <p className="font-medium">Planungsfenster hat sich verschoben</p>
                                          <p className="text-xs mt-1">Bitte prüfe, ob das Fälligkeitsdatum dieser Aufgabe noch passt.</p>
                                        </div>
                                        <button
                                          onClick={(e) => {
                                            e.stopPropagation();
                                            dismissTaskWarning(task.id);
                                          }}
                                          className="text-orange-600 hover:text-orange-800"
                                        >
                                          <X className="w-4 h-4" />
                                        </button>
                                      </div>
                                    </div>
                                  )}

                                  {task.description && (
                                    <p className="text-sm text-gray-600 mt-2">
                                      {task.description}
                                    </p>
                                  )}
                                </div>

                                <div className="flex items-center gap-2">
                                  <button
                                    onClick={(e) => {
                                      e.stopPropagation();
                                      handleEditTask(task);
                                    }}
                                    className="text-gray-400 hover:text-blue-500 transition-colors"
                                    title="Aufgabe bearbeiten"
                                  >
                                    <Edit2 className="w-5 h-5" />
                                  </button>
                                  <button
                                    onClick={(e) => {
                                      e.stopPropagation();
                                      deleteTask(task.id);
                                    }}
                                    className="text-gray-400 hover:text-rose-500 transition-colors"
                                    title="Aufgabe löschen"
                                  >
                                    <X className="w-5 h-5" />
                                  </button>
                                </div>
                              </div>

                              {task.date_change_notice && !task.completed && (
                                <div className="mt-3 p-3 bg-amber-50 border border-amber-300 rounded flex items-start gap-2">
                                  <AlertCircle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
                                  <div className="flex-1">
                                    <p className="text-sm text-amber-800">{task.date_change_notice}</p>
                                  </div>
                                  <button
                                    onClick={(e) => {
                                      e.stopPropagation();
                                      dismissDateChangeNotice(task.id);
                                    }}
                                    className="text-amber-600 hover:text-amber-800 transition-colors"
                                    title="Hinweis verwerfen"
                                  >
                                    <X className="w-4 h-4" />
                                  </button>
                                </div>
                              )}

                              <div className="flex items-center gap-3 flex-wrap mt-3">
                                <span
                                  className={`inline-flex items-center px-2 py-1 rounded text-xs text-white font-medium ${getCategoryColor(task.category)}`}
                                >
                                  {taskCategories.find(c => c.id === task.category)?.label || task.category}
                                </span>

                                <button
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    updateTask(task.id, { is_system_generated: !task.is_system_generated });
                                  }}
                                  className="text-xs text-gray-500 hover:text-gray-700 underline"
                                  title={task.is_system_generated ? 'Als manuell markieren' : 'Als automatisch markieren'}
                                >
                                  {task.is_system_generated ? '→ Manuell' : '→ Auto'}
                                </button>

                                {task.priority === 'high' && (
                                  <span className="inline-flex items-center px-2 py-1 rounded text-xs bg-rose-100 text-rose-700 font-medium">
                                    Hoch
                                  </span>
                                )}

                                {task.due_date && (
                                  <span className={`text-xs flex items-center gap-1 ${
                                    isOverdue ? 'text-rose-600 font-semibold' : 'text-gray-600'
                                  }`}>
                                    <Calendar className="w-3.5 h-3.5" />
                                    {new Date(task.due_date).toLocaleDateString('de-DE')}
                                    {isOverdue && ' (überfällig)'}
                                  </span>
                                )}

                                {task.assigned_to && (
                                  <span className="text-xs text-gray-600">
                                    Zugewiesen: {task.assigned_to}
                                  </span>
                                )}
                              </div>

                              {isBlocked && !task.completed && (
                                <div className="mt-3 p-2 bg-amber-50 border border-amber-200 rounded flex items-start gap-2">
                                  <AlertCircle className="w-4 h-4 text-amber-600 flex-shrink-0 mt-0.5" />
                                  <div className="text-sm text-amber-800">
                                    <span className="font-semibold">Wartet auf:</span> {blockedBy.join(', ')}
                                  </div>
                                </div>
                              )}
                            </div>
                          )}
                        </div>
                      );
                    })}
                    </div>
                  )}
                </div>
              );
            })
          )}
        </div>
      )}

      {showGenerateDialog && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg shadow-xl max-w-md w-full p-6">
            <h3 className="text-xl font-bold mb-4" style={{ color: '#3b3b3d' }}>
              Standard-Aufgaben generieren
            </h3>
            <p className="text-gray-700 mb-4" style={{ fontFamily: 'Open Sans, sans-serif' }}>
              Möchten Sie 40 Standard-Aufgaben automatisch erstellen?
            </p>
            <div className="bg-blue-50 border border-blue-200 rounded p-3 mb-4">
              <p className="text-sm text-blue-800">
                <span className="font-semibold">Planungszeitraum:</span><br />
                Von: <strong>{weddingData?.planning_start_date ? new Date(weddingData.planning_start_date).toLocaleDateString('de-DE') : 'Heute'}</strong><br />
                Bis: <strong>{weddingData?.wedding_date ? new Date(weddingData.wedding_date).toLocaleDateString('de-DE') : ''}</strong>
              </p>
            </div>
            <p className="text-sm text-gray-600 mb-6" style={{ fontFamily: 'Open Sans, sans-serif' }}>
              Die Aufgaben werden gleichmäßig über diesen Zeitraum verteilt.
              {!weddingData?.planning_start_date && ' Das Planungsstartdatum kann in den Einstellungen angepasst werden.'}
            </p>
            <div className="flex gap-3">
              <button
                onClick={generateStandardTasks}
                className="flex-1 px-6 py-3 rounded-md transition-all hover:opacity-90 font-semibold"
                style={{
                  backgroundColor: '#d6b15b',
                  color: 'white',
                  fontFamily: 'Open Sans, sans-serif',
                }}
              >
                Ja, erstellen
              </button>
              <button
                onClick={() => setShowGenerateDialog(false)}
                className="flex-1 px-6 py-3 rounded-md border-2 transition-all hover:bg-gray-50 font-semibold"
                style={{
                  borderColor: '#d6b15b',
                  color: '#3b3b3d',
                  fontFamily: 'Open Sans, sans-serif',
                }}
              >
                Nein, danke
              </button>
            </div>
          </div>
        </div>
      )}

      {showAddDialog && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg shadow-xl max-w-lg w-full p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-bold" style={{ color: '#3b3b3d' }}>
                Neue Aufgabe hinzufügen
              </h3>
              <button
                onClick={() => setShowAddDialog(false)}
                className="text-gray-400 hover:text-gray-600"
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: '#3b3b3d' }}>
                  Titel
                </label>
                <input
                  type="text"
                  value={newTask.title}
                  onChange={(e) => setNewTask({ ...newTask, title: e.target.value })}
                  className="w-full px-3 py-2 border-2 rounded-md"
                  style={{ borderColor: '#d6b15b' }}
                  placeholder="Aufgabentitel"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: '#3b3b3d' }}>
                  Beschreibung
                </label>
                <textarea
                  value={newTask.description}
                  onChange={(e) => setNewTask({ ...newTask, description: e.target.value })}
                  className="w-full px-3 py-2 border-2 rounded-md"
                  style={{ borderColor: '#d6b15b' }}
                  rows={3}
                  placeholder="Optionale Beschreibung"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: '#3b3b3d' }}>
                  Kategorie
                </label>
                <select
                  value={newTask.category}
                  onChange={(e) => setNewTask({ ...newTask, category: e.target.value })}
                  className="w-full px-3 py-2 border-2 rounded-md"
                  style={{ borderColor: '#d6b15b' }}
                >
                  {taskCategories.map(cat => (
                    <option key={cat.id} value={cat.id}>{cat.label}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: '#3b3b3d' }}>
                  Fälligkeitsdatum
                </label>
                <input
                  type="date"
                  value={newTask.due_date}
                  onChange={(e) => setNewTask({ ...newTask, due_date: e.target.value })}
                  className="w-full px-3 py-2 border-2 rounded-md"
                  style={{ borderColor: '#d6b15b' }}
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: '#3b3b3d' }}>
                  Priorität
                </label>
                <select
                  value={newTask.priority}
                  onChange={(e) => setNewTask({ ...newTask, priority: e.target.value as 'high' | 'medium' | 'low' })}
                  className="w-full px-3 py-2 border-2 rounded-md"
                  style={{ borderColor: '#d6b15b' }}
                >
                  <option value="low">Niedrig</option>
                  <option value="medium">Mittel</option>
                  <option value="high">Hoch</option>
                </select>
              </div>
            </div>

            <div className="flex gap-3 mt-6">
              <button
                onClick={handleAddTask}
                className="flex-1 px-6 py-3 rounded-md transition-all hover:opacity-90 font-semibold"
                style={{
                  backgroundColor: '#d6b15b',
                  color: 'white',
                  fontFamily: 'Open Sans, sans-serif',
                }}
              >
                Hinzufügen
              </button>
              <button
                onClick={() => setShowAddDialog(false)}
                className="px-6 py-3 rounded-md border-2 transition-all hover:bg-gray-50 font-semibold"
                style={{
                  borderColor: '#d6b15b',
                  color: '#3b3b3d',
                  fontFamily: 'Open Sans, sans-serif',
                }}
              >
                Abbrechen
              </button>
            </div>
          </div>
        </div>
      )}

      {showRecalculateDialog && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg shadow-xl max-w-md w-full p-6">
            <h3 className="text-xl font-bold mb-4" style={{ color: '#3b3b3d' }}>
              Automatische Tasks neu berechnen
            </h3>
            <p className="text-gray-700 mb-4" style={{ fontFamily: 'Open Sans, sans-serif' }}>
              Möchtest du alle <strong>automatischen Empfehlungen</strong> (🤖) basierend auf deinem aktuellen Hochzeitsdatum{' '}
              <strong>{weddingData?.wedding_date ? new Date(weddingData.wedding_date).toLocaleDateString('de-DE') : ''}</strong>{' '}
              neu berechnen?
            </p>
            <p className="text-gray-700 mb-4" style={{ fontFamily: 'Open Sans, sans-serif' }}>
              {tasks.filter(t => t.is_system_generated && !t.completed && !t.manually_modified).length} unveränderte Tasks werden neu erstellt.{' '}
              {tasks.filter(t => t.is_system_generated && !t.completed && t.manually_modified).length} angepasste Tasks erhalten einen Hinweis.
            </p>
            <p className="text-gray-700 mb-6" style={{ fontFamily: 'Open Sans, sans-serif' }}>
              Deine eigenen Tasks mit 💍 bleiben unverändert.
            </p>
            <div className="bg-blue-50 border border-blue-200 rounded p-3 mb-6">
              <p className="text-sm text-blue-800">
                <span className="font-semibold">Info:</span> Angepasste Tasks werden nicht überschrieben, sondern bekommen nur einen Hinweis zur Überprüfung.
              </p>
            </div>
            <div className="flex gap-3">
              <button
                onClick={recalculateAutoTaskDates}
                className="flex-1 px-6 py-3 rounded-md transition-all hover:opacity-90 font-semibold"
                style={{
                  backgroundColor: '#d6b15b',
                  color: 'white',
                  fontFamily: 'Open Sans, sans-serif',
                }}
              >
                Ja, neu berechnen
              </button>
              <button
                onClick={() => setShowRecalculateDialog(false)}
                className="flex-1 px-6 py-3 rounded-md border-2 transition-all hover:bg-gray-50 font-semibold"
                style={{
                  borderColor: '#d6b15b',
                  color: '#3b3b3d',
                  fontFamily: 'Open Sans, sans-serif',
                }}
              >
                Abbrechen
              </button>
            </div>
          </div>
        </div>
      )}

      {showEditDialog && editingTask && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg shadow-xl max-w-lg w-full p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-bold" style={{ color: '#3b3b3d' }}>
                Aufgabe bearbeiten
              </h3>
              <button
                onClick={() => {
                  setShowEditDialog(false);
                  setEditingTask(null);
                }}
                className="text-gray-400 hover:text-gray-600"
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: '#3b3b3d' }}>
                  Titel
                </label>
                <input
                  type="text"
                  value={editingTask.title}
                  onChange={(e) => setEditingTask({ ...editingTask, title: e.target.value })}
                  className="w-full px-3 py-2 border-2 rounded-md"
                  style={{ borderColor: '#d6b15b' }}
                  placeholder="Aufgabentitel"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: '#3b3b3d' }}>
                  Beschreibung
                </label>
                <textarea
                  value={editingTask.description || ''}
                  onChange={(e) => setEditingTask({ ...editingTask, description: e.target.value })}
                  className="w-full px-3 py-2 border-2 rounded-md"
                  style={{ borderColor: '#d6b15b' }}
                  rows={3}
                  placeholder="Optionale Beschreibung"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: '#3b3b3d' }}>
                  Kategorie
                </label>
                <select
                  value={editingTask.category}
                  onChange={(e) => setEditingTask({ ...editingTask, category: e.target.value })}
                  className="w-full px-3 py-2 border-2 rounded-md"
                  style={{ borderColor: '#d6b15b' }}
                >
                  {taskCategories.map(cat => (
                    <option key={cat.id} value={cat.id}>{cat.label}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: '#3b3b3d' }}>
                  Fälligkeitsdatum
                </label>
                <input
                  type="date"
                  value={editingTask.due_date || ''}
                  onChange={(e) => setEditingTask({ ...editingTask, due_date: e.target.value })}
                  className="w-full px-3 py-2 border-2 rounded-md"
                  style={{ borderColor: '#d6b15b' }}
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1" style={{ color: '#3b3b3d' }}>
                  Priorität
                </label>
                <select
                  value={editingTask.priority}
                  onChange={(e) => setEditingTask({ ...editingTask, priority: e.target.value as 'high' | 'medium' | 'low' })}
                  className="w-full px-3 py-2 border-2 rounded-md"
                  style={{ borderColor: '#d6b15b' }}
                >
                  <option value="low">Niedrig</option>
                  <option value="medium">Mittel</option>
                  <option value="high">Hoch</option>
                </select>
              </div>

              {editingTask.is_system_generated && (
                <div className="bg-blue-50 border border-blue-200 rounded p-3">
                  <p className="text-sm text-blue-800">
                    <span className="font-semibold">Hinweis:</span> Diese Aufgabe ist eine automatische Empfehlung.
                    Änderungen markieren sie als "Angepasst" und sie wird bei Datumsänderungen nicht mehr überschrieben.
                  </p>
                </div>
              )}
            </div>

            <div className="flex gap-3 mt-6">
              <button
                onClick={handleSaveEdit}
                className="flex-1 px-6 py-3 rounded-md transition-all hover:opacity-90 font-semibold"
                style={{
                  backgroundColor: '#d6b15b',
                  color: 'white',
                  fontFamily: 'Open Sans, sans-serif',
                }}
              >
                Speichern
              </button>
              <button
                onClick={() => {
                  setShowEditDialog(false);
                  setEditingTask(null);
                }}
                className="px-6 py-3 rounded-md border-2 transition-all hover:bg-gray-50 font-semibold"
                style={{
                  borderColor: '#d6b15b',
                  color: '#3b3b3d',
                  fontFamily: 'Open Sans, sans-serif',
                }}
              >
                Abbrechen
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
